(cl:defpackage std_srvs-srv
  (:use )
  (:export
   "EMPTY"
   "<EMPTY-REQUEST>"
   "EMPTY-REQUEST"
   "<EMPTY-RESPONSE>"
   "EMPTY-RESPONSE"
   "SETBOOL"
   "<SETBOOL-REQUEST>"
   "SETBOOL-REQUEST"
   "<SETBOOL-RESPONSE>"
   "SETBOOL-RESPONSE"
   "TRIGGER"
   "<TRIGGER-REQUEST>"
   "TRIGGER-REQUEST"
   "<TRIGGER-RESPONSE>"
   "TRIGGER-RESPONSE"
  ))

